import { Grenze_Gotisch, Montserrat } from "next/font/google";
import "./globals.css";

const grenzeGotisch = Grenze_Gotisch({
  subsets: ["latin"],
  weight: ["100", "400", "700", "900"], // всички нужни тежести
  style: "normal",
  variable: "--font-grenze", // по желание CSS variable
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "400", "700", "900"],
  style: ["normal", "italic"],
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         {children}
//       </body>
//     </html>
//   );
// }

import "./globals.css";
import Link from "next/link";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta
          name="description"
          content="Altar Tattoo Studio – Tattoo designs, piercing, body modifications, and art showcase in Sofia, Bulgaria."
        />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {/* <meta charset="UTF-8" /> */}
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Altar Tattoo Studio</title>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Grenze+Gotisch:wght@100..900&family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <header>
          {/* <div className="contacts">
            <div className="address">
              <p>Address: Han Asparuh 28, Sofia, Bulgaria 1000</p>
            </div>
            <div className="contact">
              <p>Tel: 0888001122</p>
              <p>9:00 - 18:00</p>
            </div>
          </div> */}
          <nav className="navbar">
            <ul>
              <Link href="/">Home</Link>
              <Link href="/#contact">Contacts</Link>
              <Link href="/#artists">Artists</Link>
              <img src="/Altar-tattoo-studio/logo.png" alt="Logo" />
              <Link href="/">About</Link>
              <Link href="/">Shop</Link>
              <Link href="/#showcaase">Showcase</Link>
            </ul>
          </nav>
        </header>

        <main>{children}</main>

        <footer>
          <div className="footer">
            <div className="footer-logo">
              <img src="/Altar-tattoo-studio/logo.png" alt="logo" />
              <h4>Altar Tattoo Sofia</h4>
            </div>
            <div className="footer-contacts">
              <p>Contact us</p>
              <h3>+359 887 663 355</h3>
              <a
                href="https://www.google.bg/maps/place/%D0%9E%D0%BB%D1%82%D0%B0%D1%80/@42.689527,23.3200823,17z/data=!3m1!4b1!4m6!3m5!1s0x40aa851287e0c8b5:0xf3f2fb1c8a21c3f7!8m2!3d42.689527!4d23.3200823!16s%2Fg%2F11b635xrst?entry=ttu&g_ep=EgoyMDI1MDMxOC4wIKXMDSoASAFQAw%3D%3D"
                target="_blank"
                rel="noopener noreferrer"
              >
                Han Asparuh 28, Sofia, Bulgaria 1000
              </a>
              <a href="mailto:altar@tattoo.com">altar@tattoo.com</a>
            </div>
            <div className="footer-working-time">
              <p>Working hours</p>
              <p>Monday: .......... 9:00 - 18:00</p>
              <p>Tuesday: .......... 9:00 - 18:00</p>
              <p>Wednesday: ...... 9:00 - 18:00</p>
              <p>Thursday: ......... 9:00 - 18:00</p>
              <p>Friday: ............. 9:00 - 18:00</p>
              <p>Saturday: ......... 9:00 - 18:00</p>
              <p>Sunday: day off</p>
            </div>
            <div className="footer-social">
              <i className="fa fa-instagram"></i>
              <i className="fa fa-facebook-square"></i>
              <i className="fa fa-reddit-square"></i>
            </div>
          </div>
          <div className="sec-footer">
            <p>© 2025 Altar Tattoo Sofia. ALL RIGHTS RESERVED.</p>
            <div className="terms">
              <a href="/">privacy policy</a>
              <a href="/">terms of service</a>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
